const events = {
  MENU_VIEWED: 'MENU_VIEWED',
  RECIPE_TAPPED: 'RECIPE_TAPPED',
  RECIPE_SUMMARY_VIEWED: 'RECIPE_SUMMARY_VIEWED',
  LOGS_VIEWED: 'LOGS_VIEWED',
  LOG_TAPPED: 'LOG_TAPPED',
  SETTINGS_VIEWED: 'SETTINGS_VIEWED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED',
}

export default events
