name: setup

runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm

    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: yarn install
