name: build-development
on:
  pull_request:
    types: [labeled, reopened, synchronize, opened]

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build:development')
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true
      - name: Build development build
        run: eas build --profile development --platform ios
