name: build
on:
  pull_request:
    types: [labeled, reopened, synchronize, opened]

jobs:
  build-development:
    name: 'EAS Build: Development'
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build:development')
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Expo GitHub Action
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: npx eas-cli build --profile development --platform ios --non-interactive
