name: build
on:
  pull_request:
    types: [labeled, reopened, synchronize, opened]

jobs:
  expo-token-check:
    name: 'Expo token check'
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        shell: bash
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
  build-development:
    name: 'EAS Build: Development'
    runs-on: ubuntu-latest
    needs: expo-token-check
    if: contains(github.event.pull_request.labels.*.name, 'build:development')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/internal-actions/setup

      - name: Build on EAS
        run: npx eas-cli build --profile development --platform ios --non-interactive
