name: build
on:
  pull_request:
    types: [labeled, reopened, synchronize, opened]

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Expo GitHub Action
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          eas-cache: true

      - name: Find cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

  build-development:
    name: 'EAS Build: Development'
    runs-on: ubuntu-latest
    needs: setup
    if: contains(github.event.pull_request.labels.*.name, 'build:development')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build development profile
        run: eas build --profile development --platform ios

  build-preview:
    name: 'EAS Build: Preview'
    runs-on: ubuntu-latest
    needs: setup
    if: contains(github.event.pull_request.labels.*.name, 'build:preview')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build preview profile
        run: eas build --profile preview --platform ios
