name: build
on:
  pull_request:
    types: [labeled, reopened, synchronize, opened]

jobs:
  build-development:
    name: EAS Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build:development')
    steps:
      - uses: ./.github/workflows/setup
      - name: Development build
        run: eas build --profile development --platform ios
  build-preview:
    name: EAS Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build:preview')
    steps:
      - uses: ./.github/workflows/setup
      - name: Preview build
        run: eas build --profile preview --platform ios
