name: update
on: push

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/internal-actions/setup
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Publish update
        run: eas update --auto
